COLLECTION_URL = "https://api.vybenetwork.xyz/nft/collection-owners/{}"
PROGRAM_DETAILS_URL="https://api.vybenetwork.xyz/program/{}"
TOP_ACTIVE_WALLETS_URL= "https://api.vybenetwork.xyz/program/{}/active-users?days={}&limit={}"
NFT_PORTFOLIO_URL="https://api.vybenetwork.xyz/account/nft-balance/{}"
WALLET_PNL_URL="https://api.vybenetwork.xyz/account/pnl/{}?resolution={}d"
WALLET_TOKEN_BALANCE_URL = "https://api.vybenetwork.xyz/account/token-balance/{}"
TOKEN_INFO_URL="https://api.vybenetwork.xyz/token/{}"
TOKEN_OHLCV_URL="https://api.vybenetwork.xyz/price/{}/token-ohlcv?resolution={}&timeStart={}&timeEnd={}"
TOP_TOKEN_HOLDERS_URL="https://api.vybenetwork.xyz/token/{}/top-holders?limit={}&sortBy={}&sortDirection={}"
PROGRAM_ACTIVE_USERS_URL="https://api.vybenetwork.xyz/program/{}/active-users-ts?range={}"
PROGRAM_TXS_URL="https://api.vybenetwork.xyz/program/{}/transactions-count-ts?range={}"
DAILY_TOP_TOKEN_HOLDERS_URL="https://api.vybenetwork.xyz/token/{}/holders-ts?startTime={}&endTime={}"
TOKEN_VOLUME_URL="https://api.vybenetwork.xyz/token/{}/transfer-volume?startTime={}&endTime={}&interval={}"
TOKEN_BALANCE_CHART_URL="https://api.vybenetwork.xyz/account/token-balance-ts/{}?days={}"
PROGRAM_TVL="https://api.vybenetwork.xyz/program/{}/tvl?resolution={}"